---
- name: Example Playbook - Test Connectivity and Gather Facts
  hosts: azure_vms
  become: yes
  gather_facts: yes

  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

    - name: Get hostname
      ansible.builtin.command: hostname
      register: hostname_output
      changed_when: false

    - name: Display hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ hostname_output.stdout }}"

    - name: Check disk space on /data
      ansible.builtin.command: df -h /data
      register: disk_space
      changed_when: false

    - name: Display disk space
      ansible.builtin.debug:
        msg: "{{ disk_space.stdout_lines }}"

    - name: Check OS version
      ansible.builtin.command: lsb_release -a
      register: os_version
      changed_when: false

    - name: Display OS version
      ansible.builtin.debug:
        msg: "{{ os_version.stdout_lines }}"
