---
- name: Configure DNS settings on Windows Jumphost
  hosts: windows_jumphosts
  gather_facts: yes

  tasks:
    - name: Get current DNS suffix search list
      win_shell: |
        Get-DnsClientGlobalSetting | Select-Object -ExpandProperty SuffixSearchList
      register: current_dns_suffix
      changed_when: false

    - name: Display current DNS suffix
      debug:
        msg: "Current DNS suffix search list: {{ current_dns_suffix.stdout_lines }}"

    - name: Set DNS suffix search list
      win_shell: |
        Set-DnsClientGlobalSetting -SuffixSearchList @("hpevme.local","5q1ivbogeb3eblqguatgczs0gh.bx.internal.cloudapp.net")
      register: dns_suffix_result

    - name: Flush DNS cache
      win_shell: |
        Clear-DnsClientCache
        ipconfig /flushdns

    - name: Verify DNS suffix configuration
      win_shell: |
        Get-DnsClientGlobalSetting | Select-Object -ExpandProperty SuffixSearchList
      register: new_dns_suffix
      changed_when: false

    - name: Display new DNS suffix
      debug:
        msg: "New DNS suffix search list: {{ new_dns_suffix.stdout_lines }}"

    - name: Test DNS resolution
      win_shell: |
        nslookup vme-kvm-vm1.hpevme.local
        nslookup jumphost.hpevme.local
        nslookup hpevme.hpevme.local
      register: dns_test
      failed_when: false
      changed_when: false

    - name: Display DNS test results
      debug:
        msg: "{{ dns_test.stdout_lines }}"

    - name: Test ping to hostnames
      win_shell: |
        ping -n 2 vme-kvm-vm1.hpevme.local
        ping -n 2 jumphost
      register: ping_test
      failed_when: false
      changed_when: false

    - name: Display ping results
      debug:
        msg: "{{ ping_test.stdout_lines }}"
