---
- name: Configure Windows Jumphost Firewall
  hosts: windows_jumphosts
  gather_facts: yes

  tasks:
    - name: Enable ICMP Echo Request (File and Printer Sharing) for all profiles
      win_shell: |
        Set-NetFirewallRule -DisplayName 'File and Printer Sharing (Echo Request - ICMPv4-In)' -Enabled True -Profile Any
        Write-Output "ICMP Echo Request enabled for all network profiles"
      register: icmp_result

    - name: Display result
      debug:
        msg: "{{ icmp_result.stdout_lines }}"

    - name: Test ICMP from jumphost to KVM hosts
      win_shell: |
        $results = @()
        $results += "Testing connectivity from jumphost:"
        $results += "Pinging vme-kvm-vm1 (10.0.2.5):"
        $results += (ping -n 2 10.0.2.5 | Select-String "Reply|Request")
        $results += ""
        $results += "Pinging vme-kvm-vm2 (10.0.2.4):"
        $results += (ping -n 2 10.0.2.4 | Select-String "Reply|Request")
        $results | Out-String
      register: connectivity_test
      failed_when: false
      changed_when: false

    - name: Display connectivity test results
      debug:
        msg: "{{ connectivity_test.stdout_lines }}"
